[package]
name = "hssp2"
version = "1.0.0"
edition = "2021"
description = "HSSP v1-3 reference implementation"
license = "MIT"
repository = "https://github.com/acridotheres/hssp2"

[dependencies]
acr = "0.3.2"
dh = "0.8.0"
